# Generated by Django 4.1 on 2022-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycharges',
            old_name='specific_pickup_point',
            new_name='specific_location',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Apple', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.CharField(default='12 GB RAM', max_length=256000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=25600000),
        ),
    ]
